from . import hotel_management_room
from . import hotel_management_facility
from . import hotel_management_food_items
from . import hotel_management_food_category
from . import hotel_management_accommodation
from . import resource_partner_extended
from . import hotel_management_order_food
from . import hotel_management_order_list
from . import hotel_management_payment
from . import hotel_management_guest
from . import hotel_gallery
