{
    'name': "Hotel Management",
    'depends': ['base', 'mail', 'sale_management', 'lunch', 'base_automation', 'website'],
    'author': "Cybrosys",
    'category': "Management",
    'installable': True,
    'application': True,
    'license': 'LGPL-3',

    'data': [
        'security/hotel_security_groups.xml',
        'security/ir.model.access.csv',
        'data/hotel_lunch_automation.xml',
        'data/default_hotel_management.xml',
        'data/sequence_accommodation.xml',
        'data/hotel_accommodation_days.xml',
        'data/hotel_management_mail.xml',
        'views/hotel_management_room.xml',
        'views/hotel_management_facility.xml',
        'views/hotel_management_food_items.xml',
        'views/hotel_management_food_category.xml',
        'views/hotel_management_accommodation.xml',
        'views/hotel_management_order_food.xml',
        'views/resource_partner_extended.xml',
        'views/hotel_mangement_guest.xml',
        'views/snippets/hotel_content.xml',
        'views/snippets/hotel_snippets.xml',
        'views/hotel_portal_templates.xml',
        'report/hotel_management_report.xml',
        'report/hotel_management_template.xml',
        'wizard/hotel_management_report_view.xml',
        'views/hotel_management_menu.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css',
            'hotel_management/static/src/css/hotel.css',
            'hotel_management/static/src/js/select2.js',
            'hotel_management/static/src/js/hotel_management_website.js',
            'hotel_management/static/src/js/hotel_gallery.js',
            'hotel_management/static/src/js/hotel_management_portal.js',
            'hotel_management/static/src/xml/hotel_website_templates.xml',
            'hotel_management/static/src/js/hotel_management_room.js',
        ],
        'web.assets_backend': [
            'hotel_management/static/src/js/action_manager.js'
        ],
    },
}
